with-expecter: true
filename: "{{.InterfaceName | snakecase}}.go"
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
packages:
    github.com/goplugin/plugin-ccip/execute/internal/gen:
        interfaces:
            ExecutePluginCodec:
    github.com/goplugin/plugin-ccip/commit/merkleroot:
        interfaces:
            Observer:
    github.com/goplugin/plugin-ccip/internal/reader:
        interfaces:
            HomeChain:
            RMNRemote:
            CCIP:
    github.com/goplugin/plugin-ccip/internal/plugincommon:
        interfaces:
            ChainSupport:
            PluginProcessor:
    github.com/goplugin/plugin-ccip/commit/merkleroot/rmn:
        interfaces:
            Controller:
            PeerGroup:
            PeerGroupFactory:
            Stream:
    github.com/goplugin/plugin-ccip/pkg/reader:
        interfaces:
            CCIPReader:
            PriceReader:
            RMNHome:
    github.com/goplugin/plugin-ccip/pkg/contractreader:
        interfaces:
            Extended:
            ContractReaderFacade:
